name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      # Set up Neo4j service for testing
      neo4j:
        image: neo4j:latest
        env:
          NEO4J_AUTH: neo4j/password123
        ports:
          - 7474:7474
          - 7687:7687
        options: >-
          --health-cmd "cypher-shell -u neo4j -p password123 'RETURN 1;'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        playwright install
    
    - name: Start LangGraph server
      run: |
        langgraph serve persona_agent:graph --port 2024 &
        sleep 10  # Give time for server to start
    
    - name: Start Streamlit app
      run: |
        streamlit run app.py &
        sleep 10  # Give time for app to start
    
    - name: Run Playwright tests
      run: |
        pytest test_app_pytest.py -v
    
    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          test-results/
          playwright-report/